name=starrocks-kafka-connector
connector.class=com.starrocks.connector.kafka.StarRocksSinkConnector
topics=temp2,temp
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=false
starrocks.http.url=starrocks-fe:8030
starrocks.topic2table.map=temp:temp_tbl,temp2:temp_tbl2
starrocks.username=user1
starrocks.password=011235813
starrocks.database.name=weather
sink.properties.strip_outer_array=true